import React from 'react';

export default class OrderOnline extends React.Component {
    render() {
        return (
            <div>
            	<h2 className="mx-4">Order Online</h2>
                <p className="mx-2">
                	<a href="https://www.trycaviar.com/t/seattle/udon--capitol-hill-3632?groups=f_online__d_clink2__p_marketing__c_merchant-links&amp;utm_medium=clink2&amp;utm_source=marketing&amp;utm_campaign=merchant-links&amp;utm_term=seattle&amp;utm_content=udon--capitol-hill-3632"><img src="https://udonseattle.files.wordpress.com/2017/04/orderdelivery.jpg?w=196" width="196" height="46" srcset="https://udonseattle.files.wordpress.com/2017/04/orderdelivery.jpg?w=196&amp;zoom=2 2x" src-orig="https://udonseattle.files.wordpress.com/2017/04/orderdelivery.jpg?w=640" scale="2"/></a>
                	<a href="https://www.trycaviar.com/t/seattle/udon--capitol-hill-3632?groups=f_online__d_clink2__p_marketing__c_merchant-links&amp;how=pickup&amp;utm_medium=localmarketing&amp;utm_source=widget&amp;utm_campaign=udon--capitol-hill-3632&amp;utm_term=seattle&amp;utm_content=udon--capitol-hill-3632&amp;cvosrc=localmarketing.widget.udon--capitol-hill-3632&amp;cvo_campaign=udon--capitol-hill-3632&amp;cav_medium=widget&amp;cav_source=udon--capitol-hill-3632"><img src="https://udonseattle.files.wordpress.com/2017/04/orderpickup.jpg?w=196" width="196" height="46" srcset="https://udonseattle.files.wordpress.com/2017/04/orderpickup.jpg?w=196&amp;zoom=2 2x" src-orig="https://udonseattle.files.wordpress.com/2017/04/orderpickup.jpg?w=640" scale="2"/></a>&nbsp; &nbsp; &nbsp;&nbsp;
                	<a href="http://www.bitesquad.com/food/u-don-capitol-hill/2366"><img data-attachment-id="1647" data-permalink="https://freshudon.com/home/button-2/" data-orig-file="https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=194&amp;h=52" data-orig-size="250,67" data-comments-opened="0" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="button-2" data-image-description="" data-medium-file="https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=194&amp;h=52?w=250" data-large-file="https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=194&amp;h=52?w=250" class="alignnone wp-image-1647" src="https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=194&amp;h=52" alt="" width="194" height="52" srcset="https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=194&amp;h=52 194w, https://udonseattle.files.wordpress.com/2011/07/button-2.png?w=150&amp;h=40 150w, https://udonseattle.files.wordpress.com/2011/07/button-2.png 250w" sizes="(max-width: 194px) 100vw, 194px"/></a>
                </p>
            </div>
        );
    }
}